module.exports = {
  SEND: 0, // XAS TRANSFER
  SIGNATURE: 1, // SETUP SECOND_PASSWORD
  DELEGATE: 2, // SECOND_PASSWORD
  VOTE: 3, // VOTE FOR DELEGATE
  MULTI: 4, // MULTISIGNATURE
  DAPP: 5, // DAPP REGISTER
  IN_TRANSFER: 6, // DAPP DEPOSIT
  OUT_TRANSFER: 7, // DAPP WITHDRAW
  STORAGE: 8, // UPLOAD STORAGE

  // UIA: USER ISSUE ASSET
  UIA_ISSUER: 9, // UIA ISSUER REGISTER
  UIA_ASSET: 10, // UIA ASSET REGISTER
  UIA_FLAGS: 11, // UIA FLAGS UPDATE
  UIA_ACL: 12, // UIA ACL UPDATE
  UIA_ISSUE: 13, // UIA ISSUE
  UIA_TRANSFER: 14, // UIA TRANSFER

  LOCK: 100 // ACCOUNT LOCK
}