module.exports = {
  SEND : 0, // XAS transfer
  SIGNATURE : 1, // setup SECOND_PASSWORD
  DELEGATE : 2, // SECOND_PASSWORD
  VOTE : 3, // vote for delegate
  MULTI: 4, // DAPP REGISTER
  DAPP: 5, // MULTISIGNATURE
  IN_TRANSFER: 6, // DAPP DEPOSIT
  OUT_TRANSFER: 7, // DAPP DEPOSIT
  STORAGE: 8, // UPLOAD STORAGE

  // UIA: User Issue Asset
  UIA_ISSUER: 9, // UIA ISSUER REGISTER
  UIA_ASSET: 10, // UIA ISSUER REGISTER
  UIA_FLAGS: 11, // UIA FLAGS UPDATE
  UIA_ACL: 12, // UIA ACL UPDATE
  UIA_ISSUE: 13, // UIA ISSUE
  UIA_TRANSFER: 14, // UIA TRANSFER

  LOCK: 100 // ACCOUNT LOCK
}