module.exports = {
  SEND : 0,
  SIGNATURE : 1,
  DELEGATE : 2,
  VOTE : 3,
  MULTI: 4,
  DAPP: 5,
  IN_TRANSFER: 6,
  OUT_TRANSFER: 7,
  STORAGE: 8,

  // UIA: User Issue Asset
  UIA_REGISTER_ISSUER: 9,
  UIA_REGISTER_ASSET: 10,
  UIA_BLACK_LIST: 11,
  UIA_WHITE_LIST: 12,
  UIA_ISSUE: 13,
  UIA_TRANSFER: 14,
  UIA_WRITE_OFF: 15
}